const Images = {
  Breakfast1: require("./Breakfast1.png"),
  Breakfast2: require("./Breakfast2.png"),
  Breakfast3: require("./Breakfast3.png"),
  Breakfast4: require("./Breakfast4.png"),
  Breakfast5: require("./Breakfast5.png"),
  Lunch1: require("./Lunch1.png"),
  Lunch2: require("./Lunch2.png"),
  Lunch3: require("./Lunch3.png"),
  Lunch4: require("./Lunch4.png"),

  Fastfood1: require("./Fastfood1.png"),
  Fastfood2: require("./Fastfood2.png"),
  Fastfood3: require("./Fastfood3.png"),
  Fastfood4: require("./Fastfood4.png"),
  Fastfood5: require("./Fastfood5.png"),
  Fastfood6: require("./Fastfood6.png"),
  Fastfood7: require("./Fastfood7.png"),
  Fastfood8: require("./Fastfood8.png"),
  drinks1: require("./drinks1.png"),
  drinks2: require("./drinks2.png"),
  drinks3: require("./drinks3.png"),
  drinks4: require("./drinks4.png"),
};
export default Images;
